Refactor, add tests to the automation workflow
Qumulo/capacity-by-user pull request #7
Opened 2021-05-12 00:22 UTC by cwboden

This is in a better spot than the 4-year-old code. However, there still could be a little more work done on `main()`:
- The tree generation and refining could be split into a helper method and unit tested
- Integration tests are missing; those these felt costly to implement
- The code could be made more object oriented

2021-08-06 17:39 UTC, NCarter3 requested changes

2021-08-06 17:39 UTC, NCarter3 commented on .gitignore
> +cython_debug/
where did this all come from? Seems like there's more in here that this project possibly needs, but if it matches across repos or the "standard" python ignore then seems fine.

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +        formatter_class=argparse.ArgumentDefaultsHelpFormatter
new behavior, call out in commit message please

2021-08-06 17:39 UTC, NCarter3 commented on requirements.txt
> +parameterized
version lock?

2021-08-06 17:39 UTC, NCarter3 commented on sample_tree_node.py
> +import heapq
we're so spoiled by stack-based workflows in mercurial...

2021-08-06 17:39 UTC, NCarter3 commented on sample_tree_node.py
> +        return self.samples < other.samples
iirc, Ezra implemented a pretty different lt method in his PR

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            return f'{capacity / float(starting_point): .2f}{unit}'
is 0.02f before functionally different?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            path=args.path, count=args.samples_to_request, by_value='capacity')
incorrect indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            args.user, args.password, args.cluster, args.port)
indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            pool, credentials_obj, args.samples, args.concurrency, args.path)
indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +                WorkerArgs(credentials, path, samples / concurrency))
indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> -@memoize
why unneeded? no appreciable speedup?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +        if user == None:
is None?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +        self.mock_client = MagicMock()
spec=?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +        self.mock_client.ad = MagicMock()
specs on all of these if possible

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +                self.owner_value)
indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +                self.mock_client, auth_id, 'NFS_UID', self.owner_value)
indentation

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +                self.owner_value)
indentation, and the ones below

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +    sublists = [(rest_client.clone(), file_ids[i:i+100]) for i in range(0, args.samples, 100)]
why clone?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +    owner_id_sublists = pool.starmap(get_file_attrs, sublists)
why starmap?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +        pool = ThreadPool(concurrency)
it's not so great to have concurrency in the test cases. It would be nice to have the concurrency abstracted in a way that the behavior tests don't need concurrency.

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user_test.py
> +        pool = ThreadPool(concurrency)
not a blocker for this PR

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            return f'[${low:.02f} - ${high:.02f}]/month'
slightly different spacing. Intentional?

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            return f'[{low_str} - {high_str}]'
different spacing

2021-08-06 17:39 UTC, NCarter3 commented on capacity_by_user.py
> +            return f'{capacity / float(starting_point):.2f}{unit}'
spacing change. Intentional?

2021-08-17 20:30 UTC, cwboden commented on capacity_by_user.py
> +    stddev = (((1 - mean) ** 2 * sample + (mean ** 4) * (num_samples
Good catch! I fixed this to leave it at `2`, but it's hard to know the intended meaning from this code 😬

2021-08-17 20:32 UTC, cwboden commented on capacity_by_user.py
> +    def sort_fn(x, y) -> int:
It sorts similar to C's `strcmp()` in that `0` means "equal", a positive value means Y > X, and a negative value means Y < X.

It's not clear, so I added a comment explaining this.

2021-08-17 20:42 UTC, cwboden commented on capacity_by_user.py
> +            return f'[${low:.02f} - ${high:.02f}]/month'
Do you mind expanding on  what you meant here? What spacing are you expecting to see?

2021-08-17 20:52 UTC, cwboden commented on capacity_by_user.py
> +            return f'[${low:.02f} - ${high:.02f}]/month'
Looking at the diff, it's clearer what you meant here. I'll address this

2021-08-17 20:55 UTC, cwboden commented on capacity_by_user.py
> +            return f'{capacity / float(starting_point):.2f}{unit}'
This is intentional, otherwise there's an extra space before the value

2021-09-22 16:16 UTC, NCarter3 approved these changes

2023-05-08 08:32 UTC, closed without merging